/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.Controle;
import modelo.Turma;
import controle.ControleFuncionario;
import excecoes.FuncionarioNaoDisponivelException;
import excecoes.PreenchimentoCamposException;
import excecoes.TurmaLotadaException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Elizeu
 */
public class CadastroTurmaForm extends javax.swing.JFrame {

    private Controle controle;
    private String[] educador_list;
    private String[] auxiliar_list;
    private String[][] matriz_alunos;
    private Turma turma_em_edicao;

    /**
     * Creates new form CadastroTurmaForm
     */
    public CadastroTurmaForm() {
        controle = new Controle();

        popula_propriedades();
        initComponents();
        popular_campos();
    }

    public void setTurma(Turma turma) {
        turma_em_edicao = turma;
    }

    public void popula_propriedades() {
        educador_list = controle.getFuncrStringArray(3);
        auxiliar_list = controle.getFuncrStringArray(4);
        matriz_alunos = controle.getAluno_Matriz();

        if (alunoCampo != null) {
            alunoCampo.setModel(new javax.swing.table.DefaultTableModel(
                    matriz_alunos,
                    new String[]{
                        "Matricula", "Nome", "Idade"
                    }
            ) {
                boolean[] canEdit = new boolean[]{
                    false, false, false
                };

                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit[columnIndex];
                }
            });
        }
    }

    public void popular_campos() {
        if (turma_em_edicao == null) {
            nomeCampo.setText("");
            salaCampo.setText("");
        } else {
            nomeCampo.setText(turma_em_edicao.getNome());
            salaCampo.setText(String.valueOf(turma_em_edicao.getSala()));

            int educadorIndex = controle.getFuncionarioIndicePorCpf(3, turma_em_edicao.getEducador().getCpf());

//            System.out.println(">>>>>>>>> " + educadorIndex + " >> " + turma_em_edicao.getEducador().getNome());
            educadorCampo.setSelectedIndex(educadorIndex);

            int auxiliarIndex = controle.getFuncionarioIndicePorCpf(4, turma_em_edicao.getAuxiliar().getCpf());
            auxiliarCampo.setSelectedIndex(auxiliarIndex);

            tipoCampo.setSelectedIndex(turma_em_edicao.getTipo());
            turnoCampo.setSelectedIndex(turma_em_edicao.getTurno());

//            System.out.println(turma_em_edicao.getAlunos().toString());
            for (int i = 0; i < alunoCampo.getRowCount(); i++) {
                String mat = alunoCampo.getValueAt(i, 0).toString();
//                System.out.println(mat);

                if (turma_em_edicao.isAlunoEmTurma(mat)) {
                    alunoCampo.getSelectionModel().addSelectionInterval(i, i);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nomeCampo = new javax.swing.JTextField();
        salaCampo = new javax.swing.JTextField();
        educadorCampo = new javax.swing.JComboBox<>();
        auxiliarCampo = new javax.swing.JComboBox<>();
        tipoCampo = new javax.swing.JComboBox<>();
        turnoCampo = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        alunoCampo = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Cadastro de Turma");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Nome");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Educador");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Auxiliar");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Limite Idade");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Sala");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Turno");

        educadorCampo.setModel(new javax.swing.DefaultComboBoxModel<>(educador_list));

        auxiliarCampo.setModel(new javax.swing.DefaultComboBoxModel<>(auxiliar_list));

        tipoCampo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Infantil 3", "Infantil 4", "Infantil 5" }));

        turnoCampo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Matutino", "Vespertino" }));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Alunos");

        alunoCampo.setModel(new javax.swing.table.DefaultTableModel(
            matriz_alunos,
            new String [] {
                "Matricula", "Nome", "Idade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(alunoCampo);

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Salvar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel6))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(55, 55, 55)
                                        .addComponent(nomeCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(56, 56, 56)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(turnoCampo, 0, 141, Short.MAX_VALUE)
                                            .addComponent(salaCampo))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tipoCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(educadorCampo, 0, 145, Short.MAX_VALUE)
                                    .addComponent(auxiliarCampo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(169, 169, 169))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE))
                        .addGap(10, 10, 10))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nomeCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(educadorCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(auxiliarCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tipoCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(salaCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(turnoCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String nome = nomeCampo.getText();
        int indice_educador = educadorCampo.getSelectedIndex();
        int indice_auxiliar = auxiliarCampo.getSelectedIndex();
        int tipo = tipoCampo.getSelectedIndex();
        String sala = salaCampo.getText();
        int turno = turnoCampo.getSelectedIndex();

        int[] row_indexes = alunoCampo.getSelectedRows();
        String alunos[][] = new String[row_indexes.length][3];
        for (int i = 0; i < row_indexes.length; i++) {
            alunos[i][0] = alunoCampo.getValueAt(row_indexes[i], 0).toString();
            alunos[i][1] = alunoCampo.getValueAt(row_indexes[i], 1).toString();
            alunos[i][2] = alunoCampo.getValueAt(row_indexes[i], 2).toString();
        }

        try {
            if (turma_em_edicao == null) {
                controle.cadastrarTurma(nome, indice_educador, indice_auxiliar, tipo, sala, turno, alunos);
            } else {
                controle.editarTurma(turma_em_edicao, nome, indice_educador, indice_auxiliar, tipo, sala, turno, alunos);
            }

            dispose();
        } catch (PreenchimentoCamposException ex) {
            PopUps.showMessage(ex.getMessage());
        } catch (FuncionarioNaoDisponivelException ex) {
            PopUps.showMessage(ex.getMessage());
        } catch (TurmaLotadaException ex) {
            PopUps.showMessage(ex.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable alunoCampo;
    private javax.swing.JComboBox<String> auxiliarCampo;
    private javax.swing.JComboBox<String> educadorCampo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nomeCampo;
    private javax.swing.JTextField salaCampo;
    private javax.swing.JComboBox<String> tipoCampo;
    private javax.swing.JComboBox<String> turnoCampo;
    // End of variables declaration//GEN-END:variables
}
