/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.Controle;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import modelo.Funcionario;
import modelo.FuncionarioInterface;

/**
 *
 * @author Elizeu
 */
public class CadastroFuncionarioForm extends javax.swing.JFrame {

    private Controle controle;
    private FuncionarioInterface funcionario_em_cadastro;

    /**
     * Creates new form CadastroFuncionarioForm
     */
    public CadastroFuncionarioForm() {
        controle = new Controle();
        funcionario_em_cadastro = null;

        popular_propriedades();
        initComponents();
        popular_campos();

    }

    public void popular_propriedades() {

    }

    public void popular_campos() {
        if (funcionario_em_cadastro != null) {
            numeromatricula.setText(funcionario_em_cadastro.getMatricula());
            nome.setText(funcionario_em_cadastro.getNome());
            senha.setText(funcionario_em_cadastro.getSenha());

            if (funcionario_em_cadastro.getSexo() == 1) {
                sexom.setSelected(true);
                sexof.setSelected(false);
            } else {
                sexom.setSelected(false);
                sexof.setSelected(true);
            }

//            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
//            String stringDate = sdf.format(funcionario_em_cadastro.getData_admissao());
//            this.data.setText(stringDate);
            cpf.setText(String.valueOf(funcionario_em_cadastro.getCpf()));
//            rg.setText(String.valueOf(funcionario_em_cadastro.getRg()));
            telefone.setText(String.valueOf(funcionario_em_cadastro.getTelefone()));
//            telefonecomercial.setText(String.valueOf(funcionario_em_cadastro.getTelefone2()));
            email.setText(String.valueOf(funcionario_em_cadastro.getEmail()));
//            endereco.setText(String.valueOf(funcionario_em_cadastro.getEndereco()));

            if (funcionario_em_cadastro.isAtivo()) {
                ativo.setSelected(true);
                inativo.setSelected(false);
//                data_demissao.setText("");
            } else {
                ativo.setSelected(false);
                inativo.setSelected(true);

//                SimpleDateFormat sdf2 = new SimpleDateFormat("dd/MM/yyyy");
//                String stringDate2 = sdf2.format(funcionario_em_cadastro.getData_demissao());
//                data_demissao.setText(stringDate2);
            }

            if (funcionario_em_cadastro.getCargo().equals("diretor")) {
                cargog.setSelected(true);
                cargos.setSelected(false);
                cargoe.setSelected(false);
                cargoa.setSelected(false);
            }

            if (funcionario_em_cadastro.getCargo().equals("secretario")) {
                cargog.setSelected(false);
                cargos.setSelected(true);
                cargoe.setSelected(false);
                cargoa.setSelected(false);
            }

            if (funcionario_em_cadastro.getCargo().equals("educador")) {
                cargog.setSelected(false);
                cargos.setSelected(false);
                cargoe.setSelected(true);
                cargoa.setSelected(false);
            }

            if (funcionario_em_cadastro.getCargo().equals("auxiliar")) {
                cargog.setSelected(false);
                cargos.setSelected(false);
                cargoe.setSelected(false);
                cargoa.setSelected(true);
            }

        } else {
            numeromatricula.setText("");
            nome.setText("");
            senha.setText("");
            sexom.setSelected(true);
            sexof.setSelected(false);
//            data.setText("");
            cpf.setText("");
//            rg.setText("");
            telefone.setText("");
//            telefonecomercial.setText("");
            email.setText("");
//            endereco.setText("");
//            data_demissao.setText("");
            ativo.setSelected(true);
            inativo.setSelected(false);

            cargog.setSelected(false);
            cargos.setSelected(true);
            cargoe.setSelected(false);
            cargoa.setSelected(false);
        }

    }

    public void setFuncionario(FuncionarioInterface funcionario) {
        funcionario_em_cadastro = funcionario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        situacao = new javax.swing.ButtonGroup();
        cargo = new javax.swing.ButtonGroup();
        sexo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        numeromatricula = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        cargog = new javax.swing.JRadioButton();
        cargoe = new javax.swing.JRadioButton();
        cargoa = new javax.swing.JRadioButton();
        cargos = new javax.swing.JRadioButton();
        sexof = new javax.swing.JRadioButton();
        sexom = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cpf = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        telefone = new javax.swing.JTextField();
        inativo = new javax.swing.JRadioButton();
        ativo = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        senha = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Cadastro de Funcionário");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Matrícula");

        numeromatricula.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        numeromatricula.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Cargo");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Nome");

        nome.setPreferredSize(new java.awt.Dimension(150, 20));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cargo.add(cargog);
        cargog.setText("Diretor");
        cargog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargogActionPerformed(evt);
            }
        });

        cargo.add(cargoe);
        cargoe.setText("Educador");

        cargo.add(cargoa);
        cargoa.setText("Auxiliar");

        cargo.add(cargos);
        cargos.setSelected(true);
        cargos.setText("Secretario");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cargog)
                    .addComponent(cargoe)
                    .addComponent(cargoa)
                    .addComponent(cargos))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(cargog)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cargos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cargoe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cargoa)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sexo.add(sexof);
        sexof.setText("Feminino");

        sexo.add(sexom);
        sexom.setSelected(true);
        sexom.setText("Masculino");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Senha");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Sexo");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("CPF");

        cpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Tel");

        telefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefoneActionPerformed(evt);
            }
        });

        situacao.add(inativo);
        inativo.setText("Inativo");

        situacao.add(ativo);
        ativo.setSelected(true);
        ativo.setText("Ativo");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Situação");

        jButton2.setText("Salvar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Email");

        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(16, 16, 16)
                                    .addComponent(jLabel1))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(69, 69, 69)
                                    .addComponent(numeromatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel2))
                                    .addGap(91, 91, 91)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(nome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(sexom)
                                                    .addGap(10, 10, 10)
                                                    .addComponent(sexof))
                                                .addComponent(senha, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(0, 0, Short.MAX_VALUE)))
                                    .addGap(18, 18, 18))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addGap(109, 109, 109)
                                    .addComponent(cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(2, 2, 2)
                                    .addComponent(jLabel5)))
                            .addGap(21, 21, 21)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)
                            .addComponent(jLabel3))
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ativo)
                                .addGap(10, 10, 10)
                                .addComponent(inativo))
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 8, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(numeromatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(senha, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sexom)
                            .addComponent(sexof)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ativo)
                    .addComponent(inativo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfActionPerformed

    }//GEN-LAST:event_cpfActionPerformed

    private void telefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefoneActionPerformed

    }//GEN-LAST:event_telefoneActionPerformed

    private void cargogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargogActionPerformed

    }//GEN-LAST:event_cargogActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        String mat = "";
        try {
//            controle.add_user(nome.getText(),
//                    senha.getText(),
//                    data.getText(),
//                    Integer.parseInt(cpf.getText()),
//                    Integer.parseInt(rg.getText()),
//                    Integer.parseInt(telefone.getText()),
//                    Integer.parseInt(celular.getText()),
//                    Integer.parseInt(telefonecomercial.getText()),
//                    email.getText(),
//                    endereco.getText());

            boolean sexo_m = this.sexom.isSelected();
            boolean ativo = this.ativo.isSelected();
            int cargo = 0;
            if (cargog.isSelected()) {
                cargo = 1;
            }

            if (cargos.isSelected()) {
                cargo = 2;
            }

            if (cargoa.isSelected()) {
                cargo = 3;
            }

            if (cargoe.isSelected()) {
                cargo = 4;
            }

            if (funcionario_em_cadastro != null) {
                this.controle.editarFuncionario(
                        funcionario_em_cadastro,
                        nome.getText(),
                        senha.getText(),
                        (cpf.getText()),
                        (telefone.getText()),
                        email.getText(),
                        sexo_m ? 1 : 0,
                        cargo,
                        ativo
                );
            } else {
                mat = this.controle.addFuncionario(nome.getText(),
                        senha.getText(),
                        (cpf.getText()),
                        (telefone.getText()),
                        email.getText(),
                        sexo_m ? 1 : 0,
                        cargo,
                        ativo
                );
                numeromatricula.setText(mat + "");
            }

            dispose();

        } catch (ParseException e) {
//            e.printStackTrace();
            PopUps.showMessage(e.getMessage());
        } catch (Exception e) {
//            e.printStackTrace();
            PopUps.showMessage(e.getMessage());
        }

//        boolean validaTodosCampos = validaTodosCampos();
//        if (validaTodosCampos) {
//            JOptionPane.showMessageDialog(null, "Preencha todos os campos para continuar", "alerta", JOptionPane.ERROR_MESSAGE);
//            return;
//        }
//
//        boolean funcionarioExiste = funcionarioExiste(cpf.getText());
//        if (funcionarioExiste) {
//            JOptionPane.showMessageDialog(null, "Funcionario ja cadastrado", "alerta", JOptionPane.ERROR_MESSAGE);
//            return;
//        }
//
//        int mat = gerarMatricula();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    public boolean validaTodosCampos() {
        return nome.getText().equals("")
                || senha.getText().equals("")
                || cpf.getText().equals("")
                || telefone.getText().equals("")
                || email.getText().equals("");
    }

    public int gerarMatricula() {
        return Integer.parseInt(Calendar.getInstance().get(Calendar.YEAR) + "0001");
    }

    public boolean funcionarioExiste(String cpf) {
        return cpf.equals("jaexiste");
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ativo;
    private javax.swing.ButtonGroup cargo;
    private javax.swing.JRadioButton cargoa;
    private javax.swing.JRadioButton cargoe;
    private javax.swing.JRadioButton cargog;
    private javax.swing.JRadioButton cargos;
    private javax.swing.JTextField cpf;
    private javax.swing.JTextField email;
    private javax.swing.JRadioButton inativo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nome;
    private javax.swing.JLabel numeromatricula;
    private javax.swing.JPasswordField senha;
    private javax.swing.ButtonGroup sexo;
    private javax.swing.JRadioButton sexof;
    private javax.swing.JRadioButton sexom;
    private javax.swing.ButtonGroup situacao;
    private javax.swing.JTextField telefone;
    // End of variables declaration//GEN-END:variables

}
