/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.Controle;
import controle.ControleAdulto;
import controle.ControleAluno;
import controle.ControleFuncionario;
import excecoes.AdultoNaoEncontradoException;
import excecoes.AlunoNaoEncontradoException;
import excecoes.CredenciaisInvalidasException;
import excecoes.FuncionarioNaoEncontradoException;
import excecoes.FuncionarioSemPermissaoException;
import excecoes.TurmaNaoEncontradaException;
import java.awt.CardLayout;
import javax.swing.JFrame;
import modelo.Adulto;
import modelo.Aluno;
import modelo.FuncionarioInterface;
import modelo.Turma;

/**
 *
 * @author infotv
 */
public class Principal extends JFrame {

    /**
     * Creates new form Principal
     */
    private Controle controle;
    private CadastroFuncionarioForm cadastrofuncionario;
    private CadastroResponsaveisForm cadastroresponsaveis;
    private CadastroTurmaForm cadastroturma;
    private CadastroAlunoForm cadastoaluno;
    private RelatorioTurma relatorioturma;

    public Principal() {
        //apagar estes metodos depois
        ControleFuncionario.getInstance().escreveFuncionariosComSenhaTeste();
        ControleAdulto.getInstance().escreveAdultosTeste();
        ControleAluno.getInstance().escreveAlunosTeste();

        controle = new Controle();

        cadastrofuncionario = new CadastroFuncionarioForm();
        cadastrofuncionario.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
//
        cadastroresponsaveis = new CadastroResponsaveisForm();
        cadastroresponsaveis.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
//
        cadastroturma = new CadastroTurmaForm();
        cadastroturma.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
//
        cadastoaluno = new CadastroAlunoForm();
        cadastoaluno.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
//
        relatorioturma = new RelatorioTurma();
        relatorioturma.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
//
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Bottom = new javax.swing.JPanel();
        telaAcesso = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        campoSenha = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        campoUsuario = new javax.swing.JTextField();
        telaInicialteste = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        cadastrarResponsaveisButton = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        telaInicial = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton23 = new javax.swing.JButton();
        moduloAluno = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela_lista_alunos = new javax.swing.JTable();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton33 = new javax.swing.JButton();
        moduloEducadores = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela_lista_funcionarios = new javax.swing.JTable();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton19 = new javax.swing.JButton();
        moduloTurmas = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabela_lista_turmas = new javax.swing.JTable();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton36 = new javax.swing.JButton();
        moduloRelatorio = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabela_relatorio_turma = new javax.swing.JTable();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        moduloResponsaveis = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tabela_lista_responsaveis = new javax.swing.JTable();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jButton38 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Bottom.setLayout(new java.awt.CardLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ClicEstrelinha");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Usuario");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Senha");

        jButton1.setText("Entrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(campoUsuario)
                                .addComponent(campoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(campoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout telaAcessoLayout = new javax.swing.GroupLayout(telaAcesso);
        telaAcesso.setLayout(telaAcessoLayout);
        telaAcessoLayout.setHorizontalGroup(
            telaAcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaAcessoLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );
        telaAcessoLayout.setVerticalGroup(
            telaAcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaAcessoLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        Bottom.add(telaAcesso, "telaAcesso");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("ClickEstrelinha");

        jButton2.setText("Cadastrar Funcionario");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Cadastrar Turma");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Cadastrar Ordens de Restrição");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Gerar Relatório de Turma");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Associar Aluno a Turma");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        cadastrarResponsaveisButton.setText("Cadastrar Pais/Responsáveis");
        cadastrarResponsaveisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarResponsaveisButtonActionPerformed(evt);
            }
        });

        jButton8.setText("Cadastrar Aluno");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Sair");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout telaInicialtesteLayout = new javax.swing.GroupLayout(telaInicialteste);
        telaInicialteste.setLayout(telaInicialtesteLayout);
        telaInicialtesteLayout.setHorizontalGroup(
            telaInicialtesteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaInicialtesteLayout.createSequentialGroup()
                .addGroup(telaInicialtesteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(telaInicialtesteLayout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel8))
                    .addGroup(telaInicialtesteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton3))
                    .addGroup(telaInicialtesteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton4))
                    .addGroup(telaInicialtesteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton5))
                    .addGroup(telaInicialtesteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton6))
                    .addGroup(telaInicialtesteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cadastrarResponsaveisButton))
                    .addGroup(telaInicialtesteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton8)))
                .addContainerGap(127, Short.MAX_VALUE))
            .addGroup(telaInicialtesteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton9)
                .addGap(116, 116, 116))
        );
        telaInicialtesteLayout.setVerticalGroup(
            telaInicialtesteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaInicialtesteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(telaInicialtesteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cadastrarResponsaveisButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton8)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        Bottom.add(telaInicialteste, "telaInicialteste");

        jButton10.setText("Sair");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText("Cadastrar funcionario");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("Cadastro de Aluno");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setText("Relatorios");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton16.setText("Cadastrar Turma");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Tela Inicial - ClicEstrelinha");

        jButton23.setText("Cadastrar Pais/Responsáveis");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout telaInicialLayout = new javax.swing.GroupLayout(telaInicial);
        telaInicial.setLayout(telaInicialLayout);
        telaInicialLayout.setHorizontalGroup(
            telaInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaInicialLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(telaInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(telaInicialLayout.createSequentialGroup()
                        .addGroup(telaInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton23, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                            .addComponent(jButton16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton10)))
                .addContainerGap())
        );
        telaInicialLayout.setVerticalGroup(
            telaInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaInicialLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(telaInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton12)
                    .addComponent(jButton10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton23)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        Bottom.add(telaInicial, "telaInicial");

        tabela_lista_alunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Matrícula", "Nome",  "Idade"
            }
        ));
        jScrollPane1.setViewportView(tabela_lista_alunos);

        jButton17.setText("Voltar");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jButton18.setText("Adicionar");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jButton20.setText("Editar");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Módulo Alunos");

        jButton33.setText("Atualizar");
        jButton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton33ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout moduloAlunoLayout = new javax.swing.GroupLayout(moduloAluno);
        moduloAluno.setLayout(moduloAlunoLayout);
        moduloAlunoLayout.setHorizontalGroup(
            moduloAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(moduloAlunoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(moduloAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, moduloAlunoLayout.createSequentialGroup()
                        .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton17))
                    .addGroup(moduloAlunoLayout.createSequentialGroup()
                        .addComponent(jButton33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 74, Short.MAX_VALUE)))
                .addContainerGap())
        );
        moduloAlunoLayout.setVerticalGroup(
            moduloAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(moduloAlunoLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(moduloAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jButton33))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(moduloAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton17)
                    .addComponent(jButton18)
                    .addComponent(jButton20))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        Bottom.add(moduloAluno, "moduloAluno");

        tabela_lista_funcionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Cargo", "CPF", "Matrícula"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabela_lista_funcionarios);
        if (tabela_lista_funcionarios.getColumnModel().getColumnCount() > 0) {
            tabela_lista_funcionarios.getColumnModel().getColumn(0).setResizable(false);
            tabela_lista_funcionarios.getColumnModel().getColumn(1).setResizable(false);
            tabela_lista_funcionarios.getColumnModel().getColumn(2).setResizable(false);
            tabela_lista_funcionarios.getColumnModel().getColumn(3).setResizable(false);
        }

        jButton21.setText("Voltar");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });

        jButton22.setText("Adicionar");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });

        jButton24.setText("Editar");
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Módulo Funcionários");

        jButton19.setText("Atualizar");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout moduloEducadoresLayout = new javax.swing.GroupLayout(moduloEducadores);
        moduloEducadores.setLayout(moduloEducadoresLayout);
        moduloEducadoresLayout.setHorizontalGroup(
            moduloEducadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(moduloEducadoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(moduloEducadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, moduloEducadoresLayout.createSequentialGroup()
                        .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton24, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton21))
                    .addGroup(moduloEducadoresLayout.createSequentialGroup()
                        .addComponent(jButton19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        moduloEducadoresLayout.setVerticalGroup(
            moduloEducadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(moduloEducadoresLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(moduloEducadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jButton19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(moduloEducadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton21)
                    .addComponent(jButton22)
                    .addComponent(jButton24))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        Bottom.add(moduloEducadores, "moduloEducadores");

        tabela_lista_turmas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Ano", "Tipo", "Turno", "Sala"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tabela_lista_turmas);
        if (tabela_lista_turmas.getColumnModel().getColumnCount() > 0) {
            tabela_lista_turmas.getColumnModel().getColumn(1).setResizable(false);
            tabela_lista_turmas.getColumnModel().getColumn(2).setResizable(false);
            tabela_lista_turmas.getColumnModel().getColumn(3).setResizable(false);
            tabela_lista_turmas.getColumnModel().getColumn(4).setResizable(false);
        }

        jButton25.setText("Voltar");
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });

        jButton26.setText("Adicionar");
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });

        jButton27.setText("Excluir");
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });

        jButton28.setText("Editar");
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Módulo Turmas");

        jButton36.setText("Atualizar");
        jButton36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton36ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout moduloTurmasLayout = new javax.swing.GroupLayout(moduloTurmas);
        moduloTurmas.setLayout(moduloTurmasLayout);
        moduloTurmasLayout.setHorizontalGroup(
            moduloTurmasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(moduloTurmasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(moduloTurmasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, moduloTurmasLayout.createSequentialGroup()
                        .addComponent(jButton26, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton27, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton28, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                        .addComponent(jButton25))
                    .addGroup(moduloTurmasLayout.createSequentialGroup()
                        .addComponent(jButton36)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        moduloTurmasLayout.setVerticalGroup(
            moduloTurmasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(moduloTurmasLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(moduloTurmasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jButton36))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(moduloTurmasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton25)
                    .addComponent(jButton26)
                    .addComponent(jButton27)
                    .addComponent(jButton28))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        Bottom.add(moduloTurmas, "moduloTurmas");

        tabela_relatorio_turma.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Ano", "Situacao", "Vagas disponíveis", "Sala", "Turno"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tabela_relatorio_turma);
        if (tabela_relatorio_turma.getColumnModel().getColumnCount() > 0) {
            tabela_relatorio_turma.getColumnModel().getColumn(0).setResizable(false);
            tabela_relatorio_turma.getColumnModel().getColumn(1).setResizable(false);
            tabela_relatorio_turma.getColumnModel().getColumn(2).setResizable(false);
            tabela_relatorio_turma.getColumnModel().getColumn(3).setResizable(false);
            tabela_relatorio_turma.getColumnModel().getColumn(4).setResizable(false);
            tabela_relatorio_turma.getColumnModel().getColumn(5).setResizable(false);
        }

        jButton29.setText("Voltar");
        jButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton29ActionPerformed(evt);
            }
        });

        jButton30.setText("Visualizar");
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton30ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Módulo Relatorios");

        javax.swing.GroupLayout moduloRelatorioLayout = new javax.swing.GroupLayout(moduloRelatorio);
        moduloRelatorio.setLayout(moduloRelatorioLayout);
        moduloRelatorioLayout.setHorizontalGroup(
            moduloRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(moduloRelatorioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(moduloRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, moduloRelatorioLayout.createSequentialGroup()
                        .addComponent(jButton30, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton29))
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        moduloRelatorioLayout.setVerticalGroup(
            moduloRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(moduloRelatorioLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(moduloRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton29)
                    .addComponent(jButton30))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        Bottom.add(moduloRelatorio, "moduloRelatorio");

        tabela_lista_responsaveis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "CPF"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tabela_lista_responsaveis);
        if (tabela_lista_responsaveis.getColumnModel().getColumnCount() > 0) {
            tabela_lista_responsaveis.getColumnModel().getColumn(0).setResizable(false);
            tabela_lista_responsaveis.getColumnModel().getColumn(1).setResizable(false);
        }

        jButton34.setText("Voltar");
        jButton34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton34ActionPerformed(evt);
            }
        });

        jButton35.setText("Adicionar");
        jButton35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton35ActionPerformed(evt);
            }
        });

        jButton37.setText("Editar");
        jButton37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton37ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Módulo Responsáveis");

        jButton38.setText("Atualizar");
        jButton38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton38ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout moduloResponsaveisLayout = new javax.swing.GroupLayout(moduloResponsaveis);
        moduloResponsaveis.setLayout(moduloResponsaveisLayout);
        moduloResponsaveisLayout.setHorizontalGroup(
            moduloResponsaveisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(moduloResponsaveisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(moduloResponsaveisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, moduloResponsaveisLayout.createSequentialGroup()
                        .addComponent(jButton35, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton37, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton34))
                    .addGroup(moduloResponsaveisLayout.createSequentialGroup()
                        .addComponent(jButton38)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 86, Short.MAX_VALUE)))
                .addContainerGap())
        );
        moduloResponsaveisLayout.setVerticalGroup(
            moduloResponsaveisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(moduloResponsaveisLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(moduloResponsaveisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jButton38))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(moduloResponsaveisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton34)
                    .addComponent(jButton35)
                    .addComponent(jButton37))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        Bottom.add(moduloResponsaveis, "moduloResponsaveis");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Bottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Bottom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Bottom.getAccessibleContext().setAccessibleName("bottom_panel");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//        System.out.println(this.campoUsuario.getText());
//        System.out.println(this.campoSenha.getText());
//        System.out.println("Tamanho: " + ControleFuncionario.getInstance().getFuncionarios().size());

        try {
            if (this.controle.autenticarUsuario(this.campoUsuario.getText(), this.campoSenha.getText())) {
                this.campoUsuario.setText("");
                this.campoSenha.setText("");
                exibirTelaInicial();
            }
        } catch (CredenciaisInvalidasException ex) {
            PopUps.showMessage(ex.getMessage());
        } catch (FuncionarioNaoEncontradoException ex) {
            PopUps.showMessage(ex.getMessage());
        } catch (FuncionarioSemPermissaoException ex) {
            PopUps.showMessage(ex.getMessage());
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void exibirTelaInicial() {
        //somente diretores podem cadastrar turmas e funcionarios
        if (this.controle.usuarioSessaoIsDiretor()) {
            jButton11.setVisible(true);
            jButton16.setVisible(true);
        } else {
            jButton11.setVisible(false);
            jButton16.setVisible(false);
        }

        CardLayout cl = (CardLayout) (Bottom.getLayout());
        cl.show(Bottom, "telaInicial");
    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        cadastroturma.popular_campos();
        cadastroturma.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        cadastrofuncionario.popular_campos();
        cadastrofuncionario.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        sair();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void sair() {
        this.controle.logout();

        CardLayout cl = (CardLayout) (Bottom.getLayout());
        cl.show(Bottom, "telaAcesso");
    }

    private void cadastrarResponsaveisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarResponsaveisButtonActionPerformed
//        cadastroresponsaveis.popular_campos();
//        cadastroresponsaveis.setVisible(true);

        carregaTelaInicialModulosResponsaveis();
    }//GEN-LAST:event_cadastrarResponsaveisButtonActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed


    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        cadastoaluno.popular_campos();
        cadastoaluno.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed


    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed

        sair();
    }//GEN-LAST:event_jButton10ActionPerformed

    public void carregaTelaInicialModuloAluno() {
        String[][] aluno_matriz = controle.getAluno_Matriz();
        tabela_lista_alunos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabela_lista_alunos.setRowSelectionAllowed(true);
        tabela_lista_alunos.setColumnSelectionAllowed(false);

        tabela_lista_alunos.setModel(new javax.swing.table.DefaultTableModel(
                aluno_matriz,
                new String[]{
                    "Nome", "Matrícula", "Idade"
                }
        ));

        CardLayout cl = (CardLayout) (Bottom.getLayout());
        cl.show(Bottom, "moduloAluno");
    }

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        carregaTelaInicialModuloAluno();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        exibirTelaInicial();
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:
        exibirTelaInicial();
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        // TODO add your handling code here:
        exibirTelaInicial();
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton29ActionPerformed
        // TODO add your handling code here:
        exibirTelaInicial();
    }//GEN-LAST:event_jButton29ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
        cadastoaluno.setAluno(null);
        cadastoaluno.popular_campos();
        cadastoaluno.setVisible(true);
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
        try {
            String matricula = tabela_lista_alunos.getValueAt(tabela_lista_alunos.getSelectedRow(), 0).toString();

            Aluno aluno = controle.buscar_aluno_matricula(matricula);
            cadastoaluno.setAluno(aluno);
            cadastoaluno.popular_campos();
            cadastoaluno.setVisible(true);

        } catch (AlunoNaoEncontradoException ex) {
            PopUps.showMessage(ex.getMessage());
        } catch (Exception ex) {
            PopUps.showMessage("É necessário selecionar um item na listagem acima para editar");
        }
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton33ActionPerformed
        // TODO add your handling code here:
        carregaTelaInicialModuloAluno();
    }//GEN-LAST:event_jButton33ActionPerformed

    public void carregaTelaInicialModulosFuncionarios() {
        String[][] funcionarios_matriz = controle.getFunc_matriz();
        tabela_lista_funcionarios.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabela_lista_funcionarios.setRowSelectionAllowed(true);
        tabela_lista_funcionarios.setColumnSelectionAllowed(false);

        tabela_lista_funcionarios.setModel(new javax.swing.table.DefaultTableModel(
                funcionarios_matriz,
                new String[]{
                    "Nome", "Cargo", "CPF", "Matrícula"
                }
        ));

        CardLayout cl = (CardLayout) (Bottom.getLayout());
        cl.show(Bottom, "moduloEducadores");
    }

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        carregaTelaInicialModulosFuncionarios();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        if (!controle.usuarioSessaoIsDiretor()) {
            PopUps.showMessage("Apenas Diretores podem acessar esta área");
        } else {
            cadastrofuncionario.setFuncionario(null);
            cadastrofuncionario.popular_campos();
            cadastrofuncionario.setVisible(true);
        }
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        // TODO add your handling code here:
        try {
            int cpf = Integer.parseInt(tabela_lista_funcionarios.getValueAt(tabela_lista_funcionarios.getSelectedRow(), 2).toString());

            FuncionarioInterface funcionario = controle.buscar_funcionario_cpf(cpf);
            cadastrofuncionario.setFuncionario(funcionario);
            cadastrofuncionario.popular_campos();
            cadastrofuncionario.setVisible(true);

        } catch (FuncionarioNaoEncontradoException ex) {
            PopUps.showMessage(ex.getMessage());
        } catch (Exception ex) {
            PopUps.showMessage("É necessário selecionar um item na listagem acima para editar");
        }
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
        carregaTelaInicialModulosFuncionarios();
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton34ActionPerformed
        // TODO add your handling code here:
        exibirTelaInicial();
    }//GEN-LAST:event_jButton34ActionPerformed

    private void jButton35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton35ActionPerformed
        // TODO add your handling code here:
        cadastroresponsaveis.popular_campos();
        cadastroresponsaveis.setVisible(true);
    }//GEN-LAST:event_jButton35ActionPerformed

    private void carregaTelaInicialModulosResponsaveis() {
        String[][] funcionarios_matriz = controle.getAdulto_Matriz();

        tabela_lista_responsaveis.setModel(new javax.swing.table.DefaultTableModel(
                new String[][]{{}, {}},
                new String[]{
                    "Nome", "CPF"
                }
        ));

        tabela_lista_responsaveis.setModel(new javax.swing.table.DefaultTableModel(
                funcionarios_matriz,
                new String[]{
                    "Nome", "CPF"
                }
        ));

        CardLayout cl = (CardLayout) (Bottom.getLayout());
        cl.show(Bottom, "moduloResponsaveis");
    }

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        // TODO add your handling code here:
        carregaTelaInicialModulosResponsaveis();
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton37ActionPerformed
        try {
            int cpf = Integer.parseInt(tabela_lista_responsaveis.getValueAt(tabela_lista_responsaveis.getSelectedRow(), 1).toString());
            Adulto adulto;

            adulto = controle.buscar_adulto_cpf(cpf);
            cadastroresponsaveis.setResposavel(adulto);
            cadastroresponsaveis.popular_campos();
            cadastroresponsaveis.setVisible(true);
        } catch (AdultoNaoEncontradoException ex) {
            PopUps.showMessage(ex.getMessage());
        } catch (Exception ex) {
            PopUps.showMessage("É necessário selecionar um item na listagem acima para editar");
        }
    }//GEN-LAST:event_jButton37ActionPerformed

    private void jButton38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton38ActionPerformed
        // TODO add your handling code here:
        carregaTelaInicialModulosResponsaveis();
    }//GEN-LAST:event_jButton38ActionPerformed

    private void carregaTelaInicialModulosTurmas() {
        String[][] turmas_matriz = controle.getTurma_matriz();
        tabela_lista_turmas.setModel(new javax.swing.table.DefaultTableModel(
                turmas_matriz,
                new String[]{
                    "Nome", "Ano", "Tipo", "Turno", "Sala"
                }
        ) {
            boolean[] canEdit = new boolean[]{
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });

        CardLayout cl = (CardLayout) (Bottom.getLayout());
        cl.show(Bottom, "moduloTurmas");
    }

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        carregaTelaInicialModulosTurmas();
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        // TODO add your handling code here:
        cadastroturma.setTurma(null);
        cadastroturma.popular_campos();
        cadastroturma.setVisible(true);
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jButton36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton36ActionPerformed
        // TODO add your handling code here:
        carregaTelaInicialModulosTurmas();
    }//GEN-LAST:event_jButton36ActionPerformed

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
        try {
            int turno = Integer.parseInt(tabela_lista_turmas.getValueAt(tabela_lista_turmas.getSelectedRow(), 3).toString());
            int sala = Integer.parseInt(tabela_lista_turmas.getValueAt(tabela_lista_turmas.getSelectedRow(), 4).toString());

            Turma turma = controle.buscar_turma(turno, sala);

            cadastroturma.setTurma(turma);
            cadastroturma.popular_campos();
            cadastroturma.setVisible(true);
        } catch (TurmaNaoEncontradaException ex) {
            PopUps.showMessage(ex.getMessage());
        } catch (Exception ex) {
            PopUps.showMessage("É necessário selecionar um item na listagem acima para editar");
        }
    }//GEN-LAST:event_jButton28ActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
        // TODO add your handling code here:
        try {
            int turno = Integer.parseInt(tabela_lista_turmas.getValueAt(tabela_lista_turmas.getSelectedRow(), 3).toString());
            int sala = Integer.parseInt(tabela_lista_turmas.getValueAt(tabela_lista_turmas.getSelectedRow(), 4).toString());
            controle.excluir_turma(turno, sala);
            carregaTelaInicialModulosTurmas();
        } catch (Exception ex) {
            PopUps.showMessage("É necessário selecionar um item na listagem acima para desativar");
        }

    }//GEN-LAST:event_jButton27ActionPerformed

    void carregaTelaInicialRelatorios() {
        String[][] relatorio_turma_matriz = controle.getRelatorio_turma_matriz();
        tabela_relatorio_turma.setModel(new javax.swing.table.DefaultTableModel(
                relatorio_turma_matriz,
                new String[]{
                    "Nome", "Ano", "Situacao", "Vagas disponíveis", "Sala", "Turno"
                }
        ) {
            boolean[] canEdit = new boolean[]{
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });

        CardLayout cl = (CardLayout) (Bottom.getLayout());
        cl.show(Bottom, "moduloRelatorio");
    }

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        carregaTelaInicialRelatorios();
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
        try {
            int sala = Integer.parseInt(tabela_relatorio_turma.getValueAt(tabela_relatorio_turma.getSelectedRow(), 4).toString());
            int turno = Integer.parseInt(tabela_relatorio_turma.getValueAt(tabela_relatorio_turma.getSelectedRow(), 5).toString());
            String situacao = tabela_relatorio_turma.getValueAt(tabela_relatorio_turma.getSelectedRow(), 2).toString();

            Turma turma = null;
            if (situacao.equals("ativo")) {
                turma = controle.buscar_turma(turno, sala);
            } else {
                turma = controle.buscar_turma_inativa(turno, sala);
            }

            relatorioturma.setTurma(turma);
            relatorioturma.popular_campos();
            relatorioturma.setVisible(true);
        } catch (TurmaNaoEncontradaException ex) {
            PopUps.showMessage(ex.getMessage());
        } catch (Exception ex) {
            PopUps.showMessage("É necessário selecionar um item na listagem acima para visualizar");
        }
    }//GEN-LAST:event_jButton30ActionPerformed

    /**
     * @param args the command line arguments
     *
     * public static void main(String args[]) { try { for
     * (javax.swing.UIManager.LookAndFeelInfo info :
     * javax.swing.UIManager.getInstalledLookAndFeels()) { if
     * ("Nimbus".equals(info.getName())) {
     * javax.swing.UIManager.setLookAndFeel(info.getClassName()); break; } } }
     * catch (ClassNotFoundException ex) {
     * java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE,
     * null, ex); } catch (InstantiationException ex) {
     * java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE,
     * null, ex); } catch (IllegalAccessException ex) {
     * java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE,
     * null, ex); } catch (javax.swing.UnsupportedLookAndFeelException ex) {
     * java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE,
     * null, ex); } //</editor-fold>
     *
     * //Create and display the form java.awt.EventQueue.invokeLater(new
     * Runnable() { public void run() { new Principal().setVisible(true); } });
     * }
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Bottom;
    private javax.swing.JButton cadastrarResponsaveisButton;
    private javax.swing.JPasswordField campoSenha;
    private javax.swing.JTextField campoUsuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JPanel moduloAluno;
    private javax.swing.JPanel moduloEducadores;
    private javax.swing.JPanel moduloRelatorio;
    private javax.swing.JPanel moduloResponsaveis;
    private javax.swing.JPanel moduloTurmas;
    private javax.swing.JTable tabela_lista_alunos;
    private javax.swing.JTable tabela_lista_funcionarios;
    private javax.swing.JTable tabela_lista_responsaveis;
    private javax.swing.JTable tabela_lista_turmas;
    private javax.swing.JTable tabela_relatorio_turma;
    private javax.swing.JPanel telaAcesso;
    private javax.swing.JPanel telaInicial;
    private javax.swing.JPanel telaInicialteste;
    // End of variables declaration//GEN-END:variables
}
